{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-10",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": ""
    },
    "Package": {
        "Registry": "pip",
        "Name": "sqlalchemy",
        "URL": "https://pypi.org/project/SQLAlchemy",
        "Downloads": "1640688"
    },
    "CWEs": [
        {
            "ID": "CWE-94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "",
        "AC": "",
        "PR": "",
        "UI": "",
        "S": "",
        "C": "",
        "I": "",
        "A": "",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "8.3"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/sqlalchemy/sqlalchemy",
        "Codebase": [
            "Python"
        ],
        "Owner": "sqlalchemy",
        "Name": "sqlalchemy",
        "Forks": "516",
        "Stars": "3272"
    },
    "Permalinks": [
        "https://drive.google.com/file/d/1ObDKJbsVSUKrhf1-yHB2H20syPOa1Kbq/view?usp=sharing"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1568",
    "FixSubmissionCount": 1
}