{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-30",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "43377443",
        "Fixer": "61599526"
    },
    "Package": {
        "Registry": "pip",
        "Name": "gita",
        "URL": "https://pypi.org/project/gita",
        "Downloads": "56"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "",
        "AC": "",
        "PR": "",
        "UI": "",
        "S": "",
        "C": "",
        "I": "",
        "A": "",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "8.0"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/nosarthur/gita",
        "Codebase": [
            "Python"
        ],
        "Owner": "nosarthur",
        "Name": "gita",
        "Forks": "42",
        "Stars": "849"
    },
    "Permalinks": [
        "https://github.com/nosarthur/gita/blob/master/gita/utils.py#L244"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1810"
}